import { ArrowRight, AudioLines, ShieldCheck } from "lucide-react";
import { SCENARIOS, type ScenarioId } from "../../scenarios/scenarios";
import type { DemoMode } from "../../hooks/useDemoController";

interface ScenarioLauncherProps { mode: DemoMode; onModeChange(mode: DemoMode): void; onSelect(scenarioId: ScenarioId): void; }
const SCENARIO_ORDER: ScenarioId[] = ["GENUINE", "HUMAN_IMPOSTOR", "AI_CLONE", "HIGH_VALUE_TRANSFER_ATTACK"];

/** Presents the deterministic scenarios before the live console begins. */
export function ScenarioLauncher({ mode, onModeChange, onSelect }: ScenarioLauncherProps) {
  const isLive = mode === "LIVE";
  return <main className="launcher-page"><header className="brand-header launcher-header"><div className="brand-lockup"><AudioLines size={21} /><span>VoxSentinel</span></div><div className="header-meta"><span className={`status-dot ${isLive ? "status-dot--green" : "status-dot--cyan"}`} /> {isLive ? "LIVE MODE" : "DEMO MODE"} <span className="meta-divider">/</span> VOICE SECURITY CONSOLE</div></header><section className="launcher-content" aria-labelledby="launcher-title"><div className="launcher-intro"><div className="eyebrow eyebrow--cyan"><span className="signal-glyph">∿</span> Real-time voice authenticity</div><h1 id="launcher-title">Choose an incident<br /><em>to investigate.</em></h1><p>{isLive ? "Connect a real microphone only when you explicitly start live analysis. The backend and model remain idle while you choose an incident." : "Run a controlled scenario through the VoxSentinel forensic workflow. Values are simulated for this demonstration."}</p><div className="mode-switch" role="group" aria-label="Analysis mode"><span className="mode-switch-label">SOURCE</span><button type="button" aria-label="Demo mode" aria-pressed={!isLive} className={`mode-switch-option ${!isLive ? "mode-switch-option--active" : ""}`} onClick={() => onModeChange("DEMO")}>DEMO</button><button type="button" aria-label="Live mode" aria-pressed={isLive} className={`mode-switch-option ${isLive ? "mode-switch-option--active" : ""}`} onClick={() => onModeChange("LIVE")}>LIVE</button></div></div><div className="scenario-list" aria-label="Demo scenarios">{SCENARIO_ORDER.map((scenarioId, index) => { const scenario = SCENARIOS[scenarioId]; const primary = scenarioId === "HIGH_VALUE_TRANSFER_ATTACK"; return <button className={`scenario-row ${primary ? "scenario-row--primary" : ""}`} key={scenarioId} onClick={() => onSelect(scenarioId)}><span className="scenario-index">0{index + 1}</span><span className="scenario-copy"><strong>{scenario.label}</strong><small>{scenario.summary}</small></span><span className="scenario-preview"><span>{scenario.events[0].overall_risk_score}</span><small>initial risk</small></span><ArrowRight className="scenario-arrow" size={18} /></button>; })}</div><div className="launcher-footnote"><ShieldCheck size={15} /><span>{isLive ? "Live backend path · Microphone starts only after explicit analysis start" : "Offline demo path · No backend connection required"}</span></div></section></main>;
}
